apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-browser-config
  namespace: default
data:
  VITE_S3_ENDPOINT: "https://s3.minio.192-168-4-113.sslip.io"
  VITE_S3_REGION: "us-east-1"
  # Values for access key and secret key should be stored in a Secret, not a ConfigMap.
  # This is for demonstration purposes only.
  # Create a secret using: kubectl create secret generic s3-credentials --from-literal=accessKeyId=... --from-literal=secretAccessKey=...
  VITE_S3_ACCESS_KEY_ID: ""
  VITE_S3_SECRET_ACCESS_KEY: ""
